#!/usr/bin/env bash

set -eou pipefail

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

nj=16
stage=-1
stop_stage=4

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/custom_manifest
#      You can download custom_manifest from https://www.openslr.org/33/
#

dl_dir=/volume/asr-experiments/godic/hubert_exp/manifest/me_youtube_no_wsp_only_zh_subset

dataset_parts="-p train -p valid"  # debug

text_extractor="pypinyin_initials_finals"
audio_extractor="Encodec"  # or Fbank
audio_feats_dir=data/tokenized

. shared/parse_options.sh || exit 1


# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare custom manifest manifest"
  mkdir -p data/manifests
  if [ ! -e data/manifests/.custom_manifest.done ]; then
    lhotse prepare custom-manifest $dl_dir data/manifests
    touch data/manifests/.custom_manifest.done
  fi
fi


if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Tokenize/Fbank custom_manifest"
  mkdir -p ${audio_feats_dir}
  if [ ! -e ${audio_feats_dir}/.custom_manifest.tokenize.done ]; then
    python3 bin/tokenizer.py --dataset-parts "${dataset_parts}" \
        --text-extractor ${text_extractor} \
        --audio-extractor ${audio_extractor} \
        --batch-duration 400 \
        --prefix "custom_manifest" \
        --src-dir "data/manifests" \
        --output-dir "${audio_feats_dir}"
  fi
  touch ${audio_feats_dir}/.custom_manifest.tokenize.done
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Prepare custom_manifest train/valid"
  if [ ! -e ${audio_feats_dir}/.custom_manifest.train.done ]; then

    # train
    lhotse copy \
      ${audio_feats_dir}/custom_manifest_cuts_train.jsonl.gz \
      ${audio_feats_dir}/cuts_train.jsonl.gz

    # valid
    lhotse copy \
      ${audio_feats_dir}/custom_manifest_cuts_valid.jsonl.gz \
      ${audio_feats_dir}/cuts_valid.jsonl.gz

    touch ${audio_feats_dir}/.custom_manifest.train.done
  fi
fi

python3 ./bin/display_manifest_statistics.py --manifest-dir ${audio_feats_dir}
